import UserModel from "../models/UserModel";

const mockData = [
  {
    username: "bdible0",
    first_name: "Baily",
    last_name: "Dible",
    age: 18,
    description:
      "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.",
    account_type: null,
    rating: 3,
    average_return: 268.18,
    followers: 690,
    avatar:
      "https://robohash.org/consequaturidreiciendis.png?size=300x300&set=set1",
  },
  {
    username: "dkilbey1",
    first_name: "Dene",
    last_name: "Kilbey",
    age: 25,
    description: "Cras in purus eu magna vulputate luctus.",
    account_type: null,
    rating: 1,
    average_return: 249.93,
    followers: 595,
    avatar:
      "https://robohash.org/quisaccusantiumculpa.png?size=300x300&set=set1",
  },
  {
    username: "cvalasek2",
    first_name: "Christiano",
    last_name: "Valasek",
    age: 29,
    description:
      "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.",
    account_type: null,
    rating: 4,
    average_return: 86.35,
    followers: 385,
    avatar:
      "https://robohash.org/istequidemrecusandae.png?size=300x300&set=set1",
  },
  {
    username: "rodell3",
    first_name: "Ruthi",
    last_name: "O'dell",
    age: 26,
    description:
      "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.",
    account_type: null,
    rating: 2,
    average_return: 213.33,
    followers: 535,
    avatar: "https://robohash.org/veletsuscipit.png?size=300x300&set=set1",
  },
  {
    username: "mgilmour4",
    first_name: "Marla",
    last_name: "Gilmour",
    age: 26,
    description: "Nulla tempus.",
    account_type: null,
    rating: 4,
    average_return: 155.4,
    followers: 869,
    avatar: "https://robohash.org/porroexest.png?size=300x300&set=set1",
  },
  {
    username: "gbeavors5",
    first_name: "Gweneth",
    last_name: "Beavors",
    age: 24,
    description: "Aenean lectus.",
    account_type: null,
    rating: 4,
    average_return: 265.64,
    followers: 992,
    avatar: "https://robohash.org/quamquiasunt.png?size=300x300&set=set1",
  },
  {
    username: "dgrzesiak6",
    first_name: "Daven",
    last_name: "Grzesiak",
    age: 23,
    description:
      "Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.",
    account_type: null,
    rating: 3,
    average_return: 168.83,
    followers: 173,
    avatar: "https://robohash.org/autnobisaut.png?size=300x300&set=set1",
  },
  {
    username: "ndeamaya7",
    first_name: "Nolan",
    last_name: "de Amaya",
    age: 18,
    description: "Duis ac nibh.",
    account_type: null,
    rating: 3,
    average_return: 53.9,
    followers: 427,
    avatar:
      "https://robohash.org/eligendimollitiaperspiciatis.png?size=300x300&set=set1",
  },
  {
    username: "alyston8",
    first_name: "Ashla",
    last_name: "Lyston",
    age: 19,
    description:
      "In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.",
    account_type: null,
    rating: 2,
    average_return: 152.63,
    followers: 690,
    avatar: "https://robohash.org/dictaadmodi.png?size=300x300&set=set1",
  },
  {
    username: "efarraway9",
    first_name: "Ellyn",
    last_name: "Farraway",
    age: 20,
    description: "In eleifend quam a odio.",
    account_type: null,
    rating: 3,
    average_return: 165.72,
    followers: 544,
    avatar: "https://robohash.org/cumqueomnisoptio.png?size=300x300&set=set1",
  },
  {
    username: "ccolesona",
    first_name: "Carie",
    last_name: "Coleson",
    age: 24,
    description:
      "Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.",
    account_type: null,
    rating: 4,
    average_return: 285.32,
    followers: 388,
    avatar: "https://robohash.org/etvitaemolestiae.png?size=300x300&set=set1",
  },
  {
    username: "jmacranaldb",
    first_name: "Jerrie",
    last_name: "MacRanald",
    age: 24,
    description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    account_type: null,
    rating: 1,
    average_return: 206.96,
    followers: 749,
    avatar: "https://robohash.org/quietest.png?size=300x300&set=set1",
  },
  {
    username: "sbedburyc",
    first_name: "Suzie",
    last_name: "Bedbury",
    age: 21,
    description:
      "Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.",
    account_type: null,
    rating: 4,
    average_return: 237.52,
    followers: 511,
    avatar: "https://robohash.org/sedbeataesimilique.png?size=300x300&set=set1",
  },
  {
    username: "fandrieuxd",
    first_name: "Frazer",
    last_name: "Andrieux",
    age: 26,
    description:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.",
    account_type: null,
    rating: 1,
    average_return: 285.26,
    followers: 258,
    avatar:
      "https://robohash.org/sitreiciendisaccusantium.png?size=300x300&set=set1",
  },
  {
    username: "rconcannone",
    first_name: "Reggi",
    last_name: "Concannon",
    age: 22,
    description:
      "Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.",
    account_type: null,
    rating: 3,
    average_return: 232.98,
    followers: 865,
    avatar: "https://robohash.org/omnisetnihil.png?size=300x300&set=set1",
  },
  {
    username: "bromeuff",
    first_name: "Berget",
    last_name: "Romeuf",
    age: 28,
    description:
      "Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    account_type: null,
    rating: 5,
    average_return: 76.46,
    followers: 152,
    avatar: "https://robohash.org/temporibusetab.png?size=300x300&set=set1",
  },
  {
    username: "vfitchg",
    first_name: "Veronica",
    last_name: "Fitch",
    age: 21,
    description: "In quis justo. Maecenas rhoncus aliquam lacus.",
    account_type: null,
    rating: 3,
    average_return: 222.07,
    followers: 333,
    avatar: "https://robohash.org/doloreiustodicta.png?size=300x300&set=set1",
  },
  {
    username: "dgostageh",
    first_name: "Deanna",
    last_name: "Gostage",
    age: 24,
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.",
    account_type: null,
    rating: 5,
    average_return: 115.59,
    followers: 472,
    avatar: "https://robohash.org/perferendisutquia.png?size=300x300&set=set1",
  },
  {
    username: "rlivesayi",
    first_name: "Rollins",
    last_name: "Livesay",
    age: 18,
    description:
      "Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    account_type: null,
    rating: 3,
    average_return: 129.66,
    followers: 446,
    avatar: "https://robohash.org/etmaximevel.png?size=300x300&set=set1",
  },
  {
    username: "cvittorej",
    first_name: "Chrissie",
    last_name: "Vittore",
    age: 28,
    description: "Nulla nisl.",
    account_type: null,
    rating: 5,
    average_return: 267.29,
    followers: 349,
    avatar:
      "https://robohash.org/perferendisquivoluptate.png?size=300x300&set=set1",
  },
  {
    username: "htrousdellk",
    first_name: "Hali",
    last_name: "Trousdell",
    age: 23,
    description: "Curabitur convallis.",
    account_type: null,
    rating: 1,
    average_return: 146.39,
    followers: 235,
    avatar:
      "https://robohash.org/consequaturvoluptatumeligendi.png?size=300x300&set=set1",
  },
  {
    username: "fbutsonl",
    first_name: "Foss",
    last_name: "Butson",
    age: 18,
    description:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.",
    account_type: null,
    rating: 5,
    average_return: 290.31,
    followers: 778,
    avatar: "https://robohash.org/eumquodolorem.png?size=300x300&set=set1",
  },
  {
    username: "bredbornm",
    first_name: "Benedicto",
    last_name: "Redborn",
    age: 27,
    description: "Duis aliquam convallis nunc.",
    account_type: null,
    rating: 4,
    average_return: 145.35,
    followers: 738,
    avatar: "https://robohash.org/laboreatnumquam.png?size=300x300&set=set1",
  },
  {
    username: "amoremann",
    first_name: "Adan",
    last_name: "Moreman",
    age: 24,
    description:
      "Vestibulum sed magna at nunc commodo placerat. Praesent blandit.",
    account_type: null,
    rating: 3,
    average_return: 203.69,
    followers: 681,
    avatar:
      "https://robohash.org/numquamlaudantiumconsequuntur.png?size=300x300&set=set1",
  },
  {
    username: "ckincho",
    first_name: "Consuela",
    last_name: "Kinch",
    age: 25,
    description:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.",
    account_type: null,
    rating: 1,
    average_return: 112.93,
    followers: 213,
    avatar:
      "https://robohash.org/doloremquiavoluptas.png?size=300x300&set=set1",
  },
  {
    username: "jcoburnp",
    first_name: "Jeddy",
    last_name: "Coburn",
    age: 28,
    description:
      "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.",
    account_type: null,
    rating: 5,
    average_return: 254.76,
    followers: 394,
    avatar: "https://robohash.org/harumeosvel.png?size=300x300&set=set1",
  },
  {
    username: "eabadq",
    first_name: "Evelin",
    last_name: "Abad",
    age: 28,
    description:
      "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.",
    account_type: null,
    rating: 3,
    average_return: 236.28,
    followers: 793,
    avatar: "https://robohash.org/autrerumesse.png?size=300x300&set=set1",
  },
  {
    username: "gcrumpr",
    first_name: "Guntar",
    last_name: "Crump",
    age: 27,
    description:
      "Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    account_type: null,
    rating: 3,
    average_return: 227.95,
    followers: 604,
    avatar: "https://robohash.org/estexpeditaharum.png?size=300x300&set=set1",
  },
  {
    username: "bbernardis",
    first_name: "Bess",
    last_name: "Bernardi",
    age: 26,
    description:
      "Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.",
    account_type: null,
    rating: 2,
    average_return: 57.24,
    followers: 494,
    avatar: "https://robohash.org/officiisnonaut.png?size=300x300&set=set1",
  },
  {
    username: "neardt",
    first_name: "Nathaniel",
    last_name: "Eard",
    age: 29,
    description:
      "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.",
    account_type: null,
    rating: 2,
    average_return: 165.15,
    followers: 418,
    avatar:
      "https://robohash.org/saepevoluptatibusaperiam.png?size=300x300&set=set1",
  },
  {
    username: "kkahenu",
    first_name: "Keefer",
    last_name: "Kahen",
    age: 22,
    description:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    account_type: null,
    rating: 1,
    average_return: 56.01,
    followers: 183,
    avatar: "https://robohash.org/quiteneturoptio.png?size=300x300&set=set1",
  },
  {
    username: "lgerrenv",
    first_name: "Lara",
    last_name: "Gerren",
    age: 20,
    description: "Nulla mollis molestie lorem. Quisque ut erat.",
    account_type: null,
    rating: 3,
    average_return: 122.48,
    followers: 642,
    avatar: "https://robohash.org/quoetaspernatur.png?size=300x300&set=set1",
  },
  {
    username: "jliddiattw",
    first_name: "Joann",
    last_name: "Liddiatt",
    age: 28,
    description:
      "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    account_type: null,
    rating: 2,
    average_return: 270.6,
    followers: 540,
    avatar: "https://robohash.org/quidoloresvoluptas.png?size=300x300&set=set1",
  },
  {
    username: "jridesdalex",
    first_name: "Jessica",
    last_name: "Ridesdale",
    age: 27,
    description: "Maecenas tincidunt lacus at velit.",
    account_type: null,
    rating: 2,
    average_return: 64.06,
    followers: 537,
    avatar: "https://robohash.org/etatea.png?size=300x300&set=set1",
  },
  {
    username: "bstickellsy",
    first_name: "Britni",
    last_name: "Stickells",
    age: 18,
    description:
      "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.",
    account_type: null,
    rating: 4,
    average_return: 193.48,
    followers: 253,
    avatar: "https://robohash.org/nostrumestiusto.png?size=300x300&set=set1",
  },
  {
    username: "hwetheyz",
    first_name: "Hyacinthia",
    last_name: "Wethey",
    age: 30,
    description: "Vivamus vel nulla eget eros elementum pellentesque.",
    account_type: null,
    rating: 3,
    average_return: 54.38,
    followers: 995,
    avatar:
      "https://robohash.org/doloribusoptiolibero.png?size=300x300&set=set1",
  },
  {
    username: "bmcneigh10",
    first_name: "Bride",
    last_name: "McNeigh",
    age: 22,
    description:
      "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    account_type: null,
    rating: 5,
    average_return: 106.65,
    followers: 884,
    avatar: "https://robohash.org/ducimusautemsunt.png?size=300x300&set=set1",
  },
  {
    username: "fwackly11",
    first_name: "Ferdy",
    last_name: "Wackly",
    age: 21,
    description:
      "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.",
    account_type: null,
    rating: 3,
    average_return: 217.49,
    followers: 843,
    avatar: "https://robohash.org/possimuscumqueut.png?size=300x300&set=set1",
  },
  {
    username: "moloughlin12",
    first_name: "Miltie",
    last_name: "O'Loughlin",
    age: 29,
    description: "Suspendisse potenti.",
    account_type: null,
    rating: 2,
    average_return: 173.77,
    followers: 846,
    avatar: "https://robohash.org/suscipitipsamvelit.png?size=300x300&set=set1",
  },
  {
    username: "dbouzek13",
    first_name: "Dannie",
    last_name: "Bouzek",
    age: 25,
    description:
      "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.",
    account_type: null,
    rating: 1,
    average_return: 256.1,
    followers: 305,
    avatar:
      "https://robohash.org/quibusdamtemporablanditiis.png?size=300x300&set=set1",
  },
  {
    username: "cgravell14",
    first_name: "Carolee",
    last_name: "Gravell",
    age: 28,
    description:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.",
    account_type: null,
    rating: 2,
    average_return: 116.33,
    followers: 790,
    avatar: "https://robohash.org/quibusdammagniquae.png?size=300x300&set=set1",
  },
  {
    username: "tblazic15",
    first_name: "Teodoor",
    last_name: "Blazic",
    age: 24,
    description:
      "Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.",
    account_type: null,
    rating: 1,
    average_return: 125.75,
    followers: 673,
    avatar: "https://robohash.org/magnamiuread.png?size=300x300&set=set1",
  },
  {
    username: "jaicken16",
    first_name: "Janette",
    last_name: "Aicken",
    age: 21,
    description:
      "Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
    account_type: null,
    rating: 4,
    average_return: 94.62,
    followers: 424,
    avatar: "https://robohash.org/voluptatesvelneque.png?size=300x300&set=set1",
  },
  {
    username: "hmenichini17",
    first_name: "Harmonie",
    last_name: "Menichini",
    age: 22,
    description:
      "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    account_type: null,
    rating: 5,
    average_return: 234.14,
    followers: 376,
    avatar: "https://robohash.org/rerumidnisi.png?size=300x300&set=set1",
  },
  {
    username: "amarini18",
    first_name: "Arvin",
    last_name: "Marini",
    age: 26,
    description:
      "Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    account_type: null,
    rating: 4,
    average_return: 55.59,
    followers: 628,
    avatar:
      "https://robohash.org/necessitatibusvoluptasvelit.png?size=300x300&set=set1",
  },
  {
    username: "mainger19",
    first_name: "Marmaduke",
    last_name: "Ainger",
    age: 18,
    description: "Vestibulum ac est lacinia nisi venenatis tristique.",
    account_type: null,
    rating: 3,
    average_return: 181.13,
    followers: 597,
    avatar:
      "https://robohash.org/distinctiovoluptasrerum.png?size=300x300&set=set1",
  },
  {
    username: "kdemke1a",
    first_name: "Kari",
    last_name: "Demke",
    age: 25,
    description: "Aliquam erat volutpat.",
    account_type: null,
    rating: 3,
    average_return: 82.45,
    followers: 228,
    avatar: "https://robohash.org/etplaceatharum.png?size=300x300&set=set1",
  },
  {
    username: "tlackemann1b",
    first_name: "Traver",
    last_name: "Lackemann",
    age: 30,
    description: "Morbi a ipsum.",
    account_type: null,
    rating: 3,
    average_return: 167.35,
    followers: 570,
    avatar: "https://robohash.org/atatquecorrupti.png?size=300x300&set=set1",
  },
  {
    username: "dtrenholm1c",
    first_name: "Danette",
    last_name: "Trenholm",
    age: 30,
    description:
      "Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    account_type: null,
    rating: 1,
    average_return: 173.24,
    followers: 480,
    avatar: "https://robohash.org/quaminciduntex.png?size=300x300&set=set1",
  },
  {
    username: "mchilles1d",
    first_name: "Maggee",
    last_name: "Chilles",
    age: 26,
    description:
      "Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    account_type: null,
    rating: 3,
    average_return: 292.61,
    followers: 746,
    avatar:
      "https://robohash.org/eumquinecessitatibus.png?size=300x300&set=set1",
  },
  {
    username: "sscotter1e",
    first_name: "Sherlocke",
    last_name: "Scotter",
    age: 30,
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.",
    account_type: null,
    rating: 5,
    average_return: 249.08,
    followers: 277,
    avatar: "https://robohash.org/etsitquibusdam.png?size=300x300&set=set1",
  },
  {
    username: "felstob1f",
    first_name: "Feliza",
    last_name: "Elstob",
    age: 19,
    description: "Vestibulum ac est lacinia nisi venenatis tristique.",
    account_type: null,
    rating: 2,
    average_return: 91.62,
    followers: 986,
    avatar: "https://robohash.org/ducimusveniamnam.png?size=300x300&set=set1",
  },
  {
    username: "dlidgett1g",
    first_name: "Deeanne",
    last_name: "Lidgett",
    age: 24,
    description:
      "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
    account_type: null,
    rating: 4,
    average_return: 159.48,
    followers: 948,
    avatar: "https://robohash.org/veniamrerumaut.png?size=300x300&set=set1",
  },
  {
    username: "wesel1h",
    first_name: "Wilbert",
    last_name: "Esel",
    age: 30,
    description:
      "Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.",
    account_type: null,
    rating: 3,
    average_return: 68.01,
    followers: 674,
    avatar: "https://robohash.org/voluptatesetsed.png?size=300x300&set=set1",
  },
  {
    username: "khanrott1i",
    first_name: "Kettie",
    last_name: "Hanrott",
    age: 20,
    description:
      "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.",
    account_type: null,
    rating: 3,
    average_return: 207.59,
    followers: 743,
    avatar: "https://robohash.org/cummolestiaequidem.png?size=300x300&set=set1",
  },
  {
    username: "dbalazot1j",
    first_name: "Duffie",
    last_name: "Balazot",
    age: 28,
    description:
      "Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    account_type: null,
    rating: 4,
    average_return: 163.05,
    followers: 802,
    avatar:
      "https://robohash.org/rerumvoluptatemexcepturi.png?size=300x300&set=set1",
  },
  {
    username: "aharriskine1k",
    first_name: "Audy",
    last_name: "Harriskine",
    age: 27,
    description:
      "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.",
    account_type: null,
    rating: 4,
    average_return: 194.53,
    followers: 472,
    avatar: "https://robohash.org/quoquasqui.png?size=300x300&set=set1",
  },
  {
    username: "coloughran1l",
    first_name: "Celestine",
    last_name: "O' Loughran",
    age: 23,
    description:
      "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.",
    account_type: null,
    rating: 4,
    average_return: 288.59,
    followers: 313,
    avatar: "https://robohash.org/nonetpraesentium.png?size=300x300&set=set1",
  },
  {
    username: "hgath1m",
    first_name: "Harli",
    last_name: "Gath",
    age: 19,
    description:
      "Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.",
    account_type: null,
    rating: 3,
    average_return: 209.7,
    followers: 859,
    avatar:
      "https://robohash.org/impeditillumsuscipit.png?size=300x300&set=set1",
  },
  {
    username: "cgeldard1n",
    first_name: "Caprice",
    last_name: "Geldard",
    age: 28,
    description: "Nam nulla.",
    account_type: null,
    rating: 3,
    average_return: 159.96,
    followers: 790,
    avatar:
      "https://robohash.org/laboresimiliqueexercitationem.png?size=300x300&set=set1",
  },
];

const mockBusinessList = [
  {
    username: "dgrigson0",
    company_name: "Effertz Group",
    description:
      "Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.",
    rating: 1,
    location: "Bích Động",
    business_category: "Specialty Products",
    avatar:
      "https://robohash.org/veritatisaccusantiumquas.png?size=300x300&set=set1",
  },
  {
    username: "adeavall1",
    company_name: "Rosenbaum, Macejkovic and Blanda",
    description:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.",
    rating: 2,
    location: "Leubatang",
    business_category: "Specialty Products",
    avatar: "https://robohash.org/eligendinamcum.png?size=300x300&set=set1",
  },
  {
    username: "bwaber2",
    company_name: "Hermiston, Padberg and Murray",
    description: "Nulla ut erat id mauris vulputate elementum.",
    rating: 4,
    location: "Lypova Dolyna",
    business_category: "Auto Accessories",
    avatar: "https://robohash.org/estetvoluptatem.png?size=300x300&set=set1",
  },
  {
    username: "mwoolam3",
    company_name: "Jones and Sons",
    description:
      "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    rating: 5,
    location: "Aki",
    business_category: "Employment Agency",
    avatar:
      "https://robohash.org/nesciuntconsequatura.png?size=300x300&set=set1",
  },
  {
    username: "bcromblehome4",
    company_name: "Hilll, Rogahn and Blanda",
    description:
      "Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.",
    rating: 2,
    location: "Herzliya Pituah",
    business_category: "Specialty Products",
    avatar: "https://robohash.org/estquierror.png?size=300x300&set=set1",
  },
  {
    username: "tpottinger5",
    company_name: "Bartoletti and Sons",
    description:
      "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    rating: 5,
    location: "Xitou",
    business_category: "Marketing & Communications",
    avatar: "https://robohash.org/quameapraesentium.png?size=300x300&set=set1",
  },
  {
    username: "ysprouls6",
    company_name: "Stroman-Berge",
    description:
      "In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    rating: 4,
    location: "Sandaogou",
    business_category: "Marketing & Communications",
    avatar:
      "https://robohash.org/magnamistenecessitatibus.png?size=300x300&set=set1",
  },
  {
    username: "mberggren7",
    company_name: "Kilback Inc",
    description:
      "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.",
    rating: 2,
    location: "Lorena",
    business_category: "Personal Care",
    avatar: "https://robohash.org/eummaximenemo.png?size=300x300&set=set1",
  },
  {
    username: "dgiacoppoli8",
    company_name: "Reynolds LLC",
    description:
      "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.",
    rating: 2,
    location: "Charneca da Cotovia",
    business_category: "Employment Agency",
    avatar:
      "https://robohash.org/cupiditateutexcepturi.png?size=300x300&set=set1",
  },
  {
    username: "bdisbrey9",
    company_name: "Homenick-O'Keefe",
    description:
      "Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.",
    rating: 2,
    location: "Firenze",
    business_category: "Auto Accessories",
    avatar:
      "https://robohash.org/officianesciunttempore.png?size=300x300&set=set1",
  },
  {
    username: "cmollina",
    company_name: "Hartmann, Towne and Bailey",
    description:
      "Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.",
    rating: 3,
    location: "Yaransk",
    business_category: "Pet Supply Store",
    avatar: "https://robohash.org/quotemporibusullam.png?size=300x300&set=set1",
  },
  {
    username: "jallmarkb",
    company_name: "Cummerata-Christiansen",
    description:
      "Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.",
    rating: 1,
    location: "Banyutengah",
    business_category: "Specialty Products",
    avatar: "https://robohash.org/eautnumquam.png?size=300x300&set=set1",
  },
  {
    username: "whuotc",
    company_name: "Hand Inc",
    description:
      "Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.",
    rating: 1,
    location: "Sinarharapan",
    business_category: "Auto Accessories",
    avatar: "https://robohash.org/fugiatidqui.png?size=300x300&set=set1",
  },
  {
    username: "epahld",
    company_name: "Schumm-Kuhlman",
    description: "Aliquam sit amet diam in magna bibendum imperdiet.",
    rating: 3,
    location: "Gondomar",
    business_category: "Marketing & Communications",
    avatar:
      "https://robohash.org/facilissaepevoluptate.png?size=300x300&set=set1",
  },
  {
    username: "kvandenveldene",
    company_name: "Boehm, Ziemann and Sipes",
    description:
      "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
    rating: 5,
    location: "Lazaro Cardenas",
    business_category: "Personal Care",
    avatar: "https://robohash.org/voluptatemaducimus.png?size=300x300&set=set1",
  },
  {
    username: "dmoirf",
    company_name: "Rodriguez, Zboncak and Schneider",
    description:
      "Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.",
    rating: 3,
    location: "Barueri",
    business_category: "Pet Supply Store",
    avatar:
      "https://robohash.org/debitisestblanditiis.png?size=300x300&set=set1",
  },
  {
    username: "tstavesg",
    company_name: "Crooks Inc",
    description:
      "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    rating: 5,
    location: "Delta del Tigre",
    business_category: "Auto Accessories",
    avatar:
      "https://robohash.org/inventorevoluptatesea.png?size=300x300&set=set1",
  },
  {
    username: "swillowsh",
    company_name: "Gutmann-Streich",
    description:
      "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    rating: 1,
    location: "Sidayu",
    business_category: "Specialty Products",
    avatar: "https://robohash.org/esseoditexpedita.png?size=300x300&set=set1",
  },
  {
    username: "aharlandi",
    company_name: "Lynch, Lakin and Abbott",
    description:
      "Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.",
    rating: 2,
    location: "Skarbimierz Osiedle",
    business_category: "Marketing & Communications",
    avatar: "https://robohash.org/vitaequiaatque.png?size=300x300&set=set1",
  },
  {
    username: "bgluyusj",
    company_name: "Bartoletti Inc",
    description:
      "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    rating: 5,
    location: "Taurage",
    business_category: "Marketing & Communications",
    avatar: "https://robohash.org/numquamnesciuntvel.png?size=300x300&set=set1",
  },
  {
    username: "gbabbk",
    company_name: "Moen-Boyer",
    description: "Sed vel enim sit amet nunc viverra dapibus.",
    rating: 1,
    location: "Jezzîne",
    business_category: "Employment Agency",
    avatar: "https://robohash.org/temporeipsaquia.png?size=300x300&set=set1",
  },
  {
    username: "rhalbordl",
    company_name: "Marquardt, McClure and Oberbrunner",
    description:
      "In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.",
    rating: 1,
    location: "Tianchi",
    business_category: "Personal Care",
    avatar: "https://robohash.org/officiautitaque.png?size=300x300&set=set1",
  },
  {
    username: "rtabarym",
    company_name: "MacGyver, Lubowitz and Watsica",
    description:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.",
    rating: 3,
    location: "Ono",
    business_category: "Auto Accessories",
    avatar:
      "https://robohash.org/oditconsequuntureum.png?size=300x300&set=set1",
  },
  {
    username: "ehandasyden",
    company_name: "Wolff-Kirlin",
    description:
      "Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.",
    rating: 5,
    location: "Cradock",
    business_category: "Marketing & Communications",
    avatar: "https://robohash.org/corruptiomnisea.png?size=300x300&set=set1",
  },
  {
    username: "mtubbleo",
    company_name: "Olson, Hoppe and Barton",
    description:
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.",
    rating: 4,
    location: "Hongxi",
    business_category: "Personal Care",
    avatar: "https://robohash.org/voluptasfugitiste.png?size=300x300&set=set1",
  },
  {
    username: "bparlotp",
    company_name: "Kunze-Osinski",
    description:
      "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.",
    rating: 2,
    location: "Chornukhyne",
    business_category: "Specialty Products",
    avatar:
      "https://robohash.org/doloresvoluptatemconsequatur.png?size=300x300&set=set1",
  },
  {
    username: "hhalstedq",
    company_name: "Murazik, Dickinson and Cassin",
    description: "Donec dapibus. Duis at velit eu est congue elementum.",
    rating: 2,
    location: "Krzeszów",
    business_category: "Specialty Products",
    avatar:
      "https://robohash.org/facerevoluptatemeaque.png?size=300x300&set=set1",
  },
  {
    username: "rburgoinr",
    company_name: "Hand, Littel and Cole",
    description:
      "Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    rating: 5,
    location: "Zaraysk",
    business_category: "Auto Accessories",
    avatar: "https://robohash.org/minimaenimharum.png?size=300x300&set=set1",
  },
  {
    username: "gstannions",
    company_name: "Hegmann-Abshire",
    description:
      "Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.",
    rating: 1,
    location: "North Battleford",
    business_category: "Personal Care",
    avatar: "https://robohash.org/harumutnulla.png?size=300x300&set=set1",
  },
  {
    username: "efrailt",
    company_name: "Fritsch, Dach and Jenkins",
    description:
      "Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    rating: 5,
    location: "Tovarkovskiy",
    business_category: "Employment Agency",
    avatar: "https://robohash.org/remnonquas.png?size=300x300&set=set1",
  },
  {
    username: "dbyarsu",
    company_name: "Parker-Hilpert",
    description:
      "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
    rating: 3,
    location: "Moses",
    business_category: "Auto Accessories",
    avatar: "https://robohash.org/quioptiomolestiae.png?size=300x300&set=set1",
  },
  {
    username: "tolunneyv",
    company_name: "Bradtke Inc",
    description:
      "Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    rating: 4,
    location: "Watubura",
    business_category: "Auto Accessories",
    avatar:
      "https://robohash.org/consequaturvoluptasipsa.png?size=300x300&set=set1",
  },
  {
    username: "cmuscottw",
    company_name: "Schowalter and Sons",
    description:
      "Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    rating: 3,
    location: "Fukui-shi",
    business_category: "Auto Accessories",
    avatar: "https://robohash.org/nihilharumest.png?size=300x300&set=set1",
  },
  {
    username: "nfeasterx",
    company_name: "Prohaska-Goodwin",
    description:
      "In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.",
    rating: 4,
    location: "Lampuyang",
    business_category: "Auto Accessories",
    avatar: "https://robohash.org/utfugaaut.png?size=300x300&set=set1",
  },
  {
    username: "cmartyntsevy",
    company_name: "Harris-Hirthe",
    description:
      "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.",
    rating: 4,
    location: "Bau",
    business_category: "Specialty Products",
    avatar: "https://robohash.org/velearumaliquam.png?size=300x300&set=set1",
  },
  {
    username: "nfedorskiz",
    company_name: "Nicolas Inc",
    description:
      "Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.",
    rating: 4,
    location: "Péruwelz",
    business_category: "Personal Care",
    avatar: "https://robohash.org/velittemporibusaut.png?size=300x300&set=set1",
  },
  {
    username: "mphilcock10",
    company_name: "Corwin and Sons",
    description:
      "Etiam pretium iaculis justo. In hac habitasse platea dictumst.",
    rating: 4,
    location: "Gangba",
    business_category: "Employment Agency",
    avatar: "https://robohash.org/quisquiut.png?size=300x300&set=set1",
  },
  {
    username: "rqualtro11",
    company_name: "Schimmel-Russel",
    description:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.",
    rating: 2,
    location: "Huatanshan",
    business_category: "Pet Supply Store",
    avatar:
      "https://robohash.org/dolorescumconsectetur.png?size=300x300&set=set1",
  },
  {
    username: "bphillipson12",
    company_name: "Mante, Tromp and Gutkowski",
    description:
      "Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.",
    rating: 5,
    location: "Salamá",
    business_category: "Specialty Products",
    avatar: "https://robohash.org/doloresliberoodio.png?size=300x300&set=set1",
  },
  {
    username: "rkiraly13",
    company_name: "Jast Group",
    description:
      "Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.",
    rating: 2,
    location: "Nadezhda",
    business_category: "Auto Accessories",
    avatar:
      "https://robohash.org/rerumsequicupiditate.png?size=300x300&set=set1",
  },
  {
    username: "qshawel14",
    company_name: "Funk Inc",
    description:
      "Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.",
    rating: 4,
    location: "Lekas",
    business_category: "Specialty Products",
    avatar: "https://robohash.org/vitaeabimpedit.png?size=300x300&set=set1",
  },
  {
    username: "rbelfit15",
    company_name: "Barton, Rempel and Okuneva",
    description: "Aenean auctor gravida sem.",
    rating: 5,
    location: "Chelopech",
    business_category: "Pet Supply Store",
    avatar: "https://robohash.org/quiexplicaboin.png?size=300x300&set=set1",
  },
  {
    username: "aangerstein16",
    company_name: "Stokes LLC",
    description: "Ut at dolor quis odio consequat varius. Integer ac leo.",
    rating: 4,
    location: "Honoria",
    business_category: "Personal Care",
    avatar: "https://robohash.org/voluptatenihilaut.png?size=300x300&set=set1",
  },
  {
    username: "sglison17",
    company_name: "Jenkins, Schuster and Blanda",
    description: "Pellentesque eget nunc.",
    rating: 5,
    location: "Bolkhov",
    business_category: "Auto Accessories",
    avatar: "https://robohash.org/autinsit.png?size=300x300&set=set1",
  },
  {
    username: "mbritcher18",
    company_name: "Goldner and Sons",
    description:
      "Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.",
    rating: 4,
    location: "Vänersborg",
    business_category: "Marketing & Communications",
    avatar: "https://robohash.org/atqueatvoluptatum.png?size=300x300&set=set1",
  },
  {
    username: "afisby19",
    company_name: "Hackett-Hermiston",
    description:
      "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    rating: 4,
    location: "Simpang",
    business_category: "Employment Agency",
    avatar: "https://robohash.org/eosquisiure.png?size=300x300&set=set1",
  },
  {
    username: "cstanex1a",
    company_name: "Lubowitz-Klein",
    description: "Sed ante.",
    rating: 3,
    location: "Souto",
    business_category: "Personal Care",
    avatar: "https://robohash.org/solutaquirerum.png?size=300x300&set=set1",
  },
  {
    username: "dsalters1b",
    company_name: "Raynor, Treutel and Goodwin",
    description:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    rating: 3,
    location: "Rio Claro",
    business_category: "Employment Agency",
    avatar: "https://robohash.org/etnonofficiis.png?size=300x300&set=set1",
  },
  {
    username: "rtabor1c",
    company_name: "Runolfsdottir Inc",
    description: "Nunc purus.",
    rating: 4,
    location: "Mozi",
    business_category: "Marketing & Communications",
    avatar: "https://robohash.org/fugiatautemharum.png?size=300x300&set=set1",
  },
  {
    username: "mfoulstone1d",
    company_name: "Nicolas Group",
    description:
      "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    rating: 4,
    location: "Bielice",
    business_category: "Auto Accessories",
    avatar: "https://robohash.org/sedestut.png?size=300x300&set=set1",
  },
];

export const UserList = [
  new UserModel(
    "ivanpedrocr",
    "Ivan",
    "Casas",
    17,
    "Hello",
    null,
    5,
    150,
    999,
    "https://robohash.org/sedestut.png?size=300x300&set=set1"
  ),
  ...mockData.map((user) => {
    return new UserModel(
      user.username,
      user.first_name,
      user.last_name,
      user.age,
      user.description,
      user.account_type,
      user.rating,
      user.average_return,
      user.followers,
      user.avatar
    );
  }),
];

export const BusinessList = [
  ...mockBusinessList.map((business) => {
    return {
      username: business.username,
      rating: business.rating,
      description: business.description,
      businessCategory: business.business_category,
      companyName: business.company_name,
      location: business.location,
      avatar: business.avatar,
    };
  }),
];
